name: Backend Lint

on:
  push:
    paths:
      - "Backend/**"
  pull_request:
    paths:
      - "Backend/**"

jobs:
  ruff:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Check formatting
        run: ruff format . --check